// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLt5zCEdo2q4pb8KxMcHsS0V-Wqcvd08E',
    appId: '1:1078519906377:web:9716bc17ffb2fc674c3f98',
    messagingSenderId: '1078519906377',
    projectId: 'chat-x-87a45',
    authDomain: 'chat-x-87a45.firebaseapp.com',
    storageBucket: 'chat-x-87a45.firebasestorage.app',
    measurementId: 'G-G987480BWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgyV0OedHUG9_x4SJx-RkKfMY6AqPik1c',
    appId: '1:1078519906377:android:45912c202a6114734c3f98',
    messagingSenderId: '1078519906377',
    projectId: 'chat-x-87a45',
    storageBucket: 'chat-x-87a45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCMCGQv_c4gQ-z09ytnJvdrEZ5qC9GObs',
    appId: '1:1078519906377:ios:36ea8f5998bebad64c3f98',
    messagingSenderId: '1078519906377',
    projectId: 'chat-x-87a45',
    storageBucket: 'chat-x-87a45.firebasestorage.app',
    iosBundleId: 'com.example.chatx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCMCGQv_c4gQ-z09ytnJvdrEZ5qC9GObs',
    appId: '1:1078519906377:ios:36ea8f5998bebad64c3f98',
    messagingSenderId: '1078519906377',
    projectId: 'chat-x-87a45',
    storageBucket: 'chat-x-87a45.firebasestorage.app',
    iosBundleId: 'com.example.chatx',
  );
}
